language: shell

before_install:
  - npm install -g jshint

install:
  - ./qt_installer.sh

script:
  - jshint control_script.js
  - qmake --version

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env:
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-mac-x64-online.dmg"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/vars_mac.js"
        - PATH="/opt/Qt/5.12.3/clang_64/bin:${PATH}"
