language: shell

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then npm install -g jshint ; fi

install:
  - ./qt_installer.sh

script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then jshint control_script.js ; fi
  - ${PATH_5123}/qmake --version
  - ${PATH_598}/qmake --version

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env:
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-mac-x64-online.dmg"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/vars_mac.js"
        - PATH_5123="/opt/Qt/5.12.3/clang_64/bin"
        - PATH_598="/opt/Qt/5.9.8/clang_64/bin"

    # 64-bit Windows
    - os: windows
      env:
        # Yes, x86 in installer name is correct.
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-windows-x86-online.exe"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/vars_win_x64.js"
        - PATH_5123="/c/Qt/5.12.3/msvc2017_64/bin"
        - PATH_598="/c/Qt/5.9.8/msvc2017_64/bin"

    # 32-bit Windows
    - os: windows
      env:
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-windows-x86-online.exe"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/vars_win_x86.js"
        - PATH_5123="/c/Qt/5.12.3/msvc2017/bin"
        - PATH_598="/c/Qt/5.9.8/msvc2017/bin"
